### PR TITLE
Add a cronjob to purge agents daily

### PR DESCRIPTION
**Pull request by cnelson**
*BEFORE MERGING THIS!*: ensure that https://github.com/18F/cg-nessus-agent-boshrelease/pull/7 is merged and deployed to all VMs first.  That PR ensures that the agents continually try to relink themselves with the manager.

This PR will remove all agents from nessus each day so that only the active agents (which will relink themselves via the PR above) will be scanned and count against our limited license pool.

### CODE REVIEW

**Comment by mogul** [comment]
We have a [downstream support ticket](https://cloud-gov.zendesk.com/agent/tickets/134) still pending on this... Is it getting merged soon?

**Comment by cnelson** [comment]
We need to audit all our deployments and ensure they are all running release 18 of `nessus-agent`, then this can be deployed

**Comment by cnelson** [comment]
:( Things missing the current release:
- All of tooling
-  shibboleth-staging
- All of producton except diego and log search

**Comment by cnelson** [comment]
All bosh deployments in GovCloud listed above are now running the correct nessus-agent release.  I believe this is now ok to merge.  Once merged I will monitor the nessus manager to ensure it maintains an accurate list of linked agents.

**Comment by pburkholder** [comment]
But _why_ did you need to delete the agent nightly? 

https://i.kym-cdn.com/photos/images/original/000/959/623/323.jpg

**Comment by cnelson** [comment]
irrc, it was licensing related.

I think nessus was counting each new bosh managed VM as a seat, and would never automatically remove old instances, thus quickly exhausting the available seeats

not 100% sure about that though, it's been many years

**Comment by pburkholder** [comment]
Happy five year anniversary to this PR 🎉 and 🎄

**Comment by LinuxBozo** [comment]
Chris nailed it, but there is some added nuance here. So we had a de-link in the bosh nessus-agent release as well (https://github.com/cloud-gov/cg-nessus-agent-boshrelease/blob/master/jobs/nessus-agent/templates/bin/drain), but when things went missing, or the post script didn't run correctly during bosh operations, we would have a bunch of agents that were registered, but didn't actually exist. This was put in place as a backup catch all to make sure that things that didn't exist weren't registered, as things that did exist would eventually re-register themselves anyway. You'll also notice Chris has lots of comments around the "API" because none of this was really documented by Tenable. It took a bunch of investigation and experimentation to get things working. Tenable expects you to have pets for its licensing model.

**Pull request merged**
